# Generated by Django 4.2.30 on 2026-10-09 14:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('aspect', models.CharField(choices=[('16:9', '16:9'), ('4:3', '4:3')], default='16:9', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('seat', models.PositiveSmallIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('interactions', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs_url', models.CharField(max_length=255)),
                ('number_of_screens', models.IntegerField(default=4)),
                ('show_screen_id', models.BooleanField(default=False)),
                ('background_image', models.CharField(max_length=255)),
                ('background_image_on_empty_screens', models.BooleanField(default=False)),
                ('background_image_on_welcome_screens', models.BooleanField(default=False)),
                ('background_image_on_all_slides_per_default', models.BooleanField(default=False)),
                ('language', models.CharField(max_length=255)),
                ('theme', models.CharField(default='system', max_length=50)),
                ('palette', models.CharField(default='indigo', max_length=50)),
                ('carto_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar_style', models.CharField(default='glyphs', max_length=50)),
                ('dev_mode', models.BooleanField(default=False)),
                ('moderator_pin', models.CharField(max_length=128)),
                ('pin_length', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(10)])),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.event')),
            ],
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.CheckConstraint(check=models.Q(('seat__gte', 1), ('seat__lte', 99)), name='seat_range'),
        ),
        migrations.AddField(
            model_name='event',
            name='monitors',
            field=models.ManyToManyField(related_name='events', to='core.monitor'),
        ),
    ]
