# Generated by Django 5.2.15 on 2026-07-06 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('aspect', models.CharField(choices=[('16:9', '16:9'), ('4:3', '4:3')], default='16:9', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs_url', models.CharField(max_length=255)),
                ('number_of_screens', models.IntegerField(default=4)),
                ('background_image', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('width', models.IntegerField(default=1920)),
                ('height', models.IntegerField(default=1080)),
                ('tags', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('n_groups', models.IntegerField(default=3)),
                ('moderator_pin', models.CharField(blank=True, max_length=128, null=True)),
                ('monitors', models.ManyToManyField(related_name='events', to='core.monitor')),
            ],
        ),
        migrations.CreateModel(
            name='SceneInPresentationPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.presentation')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.scene')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='presentation',
            name='scenes',
            field=models.ManyToManyField(blank=True, related_name='presentations', through='core.SceneInPresentationPosition', to='core.scene'),
        ),
        migrations.CreateModel(
            name='SlideInScenePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.scene')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.slide')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='scene',
            name='slides',
            field=models.ManyToManyField(blank=True, related_name='scenes', through='core.SlideInScenePosition', to='core.slide'),
        ),
        migrations.CreateModel(
            name='SlideSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width_fraction', models.FloatField(default=1.0)),
                ('view_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('chart', 'Chart')], default='text', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('content_path', models.CharField(blank=True, max_length=255)),
                ('mode', models.CharField(blank=True, max_length=40)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.slide')),
            ],
        ),
    ]
