# Generated by Django 4.2.30 on 2026-07-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidesection',
            name='url_pattern',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='slidesection',
            name='mode',
            field=models.CharField(blank=True, choices=[('static', 'Static'), ('url', 'URL'), ('interactive', 'Interactive')], max_length=20),
        ),
    ]
