# Generated by Django 4.2.30 on 2026-07-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_slidesection_url_pattern_alter_slidesection_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='options',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
