# Generated by Django 4.2.30 on 2026-07-08 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parameter_parameterset'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='parameter_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='core.parameterset'),
            preserve_default=False,
        ),
    ]
