# Generated by Django 4.2.30 on 2026-06-04 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='slide',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 6, 4, 17, 27, 26, 390275)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
