# Generated by Django 5.2.15 on 2026-07-11 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_parameter_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivePresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('current_scene', models.IntegerField(default=0)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentation', to='core.presentation')),
            ],
        ),
    ]
