# Generated by Django 4.2.30 on 2026-06-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_title_slide_name_slide_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='moderator_pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
