# Generated by Django 5.2.15 on 2026-07-11 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_livepresentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livepresentation',
            name='presentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_presentation', to='core.presentation'),
        ),
    ]
