# Generated by Django 4.2.30 on 2026-06-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event_moderator_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
