# Generated by Django 4.2.30 on 2026-06-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_slide_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='layout',
            field=models.CharField(choices=[('full', 'Full Screen'), ('half-left', 'Half Left'), ('half-right', 'Half Right')], default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='slide',
            name='markdown',
            field=models.TextField(blank=True),
        ),
    ]
