# Generated by Django 4.2.30 on 2026-07-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_livepresentation_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidesection',
            name='properties',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
