# Generated by Django 4.2.30 on 2026-07-23 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_participant_delete_group_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='participant',
            name='identifier_range',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='identifier',
        ),
        migrations.AddField(
            model_name='participant',
            name='interactions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='seat',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.CheckConstraint(check=models.Q(('seat__gte', 1), ('seat__lte', 99)), name='seat_range'),
        ),
    ]
