# Generated by Django 4.2.30 on 2026-06-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_slide_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='height',
            field=models.IntegerField(default=1080),
        ),
        migrations.AddField(
            model_name='slide',
            name='width',
            field=models.IntegerField(default=1920),
        ),
    ]
