# Generated by Django 4.2.30 on 2026-06-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_slide_height_slide_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('aspect', models.CharField(choices=[('16:9', '16:9'), ('4:3', '4:3')], default='16:9', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='n_monitor',
        ),
        migrations.AddField(
            model_name='event',
            name='monitors',
            field=models.ManyToManyField(related_name='events', to='core.monitor'),
        ),
    ]
