# Generated by Django 4.2.30 on 2026-09-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_move_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='palette',
            field=models.CharField(default='indigo', max_length=50),
        ),
        migrations.AddField(
            model_name='settings',
            name='theme',
            field=models.CharField(default='system', max_length=50),
        ),
    ]
