# Generated by Django 4.2.30 on 2026-06-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_monitor_remove_event_n_monitor_event_monitors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scene',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='scene',
            name='slides',
            field=models.ManyToManyField(blank=True, related_name='scenes', to='core.slide'),
        ),
    ]
