# Generated by Django 4.2.30 on 2026-09-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_settings_palette_settings_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='avatar_style',
            field=models.CharField(default='glyphs', max_length=50),
        ),
        migrations.AddField(
            model_name='settings',
            name='carto_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
