# Generated by Django 4.2.30 on 2026-06-24 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_title_scene_name_scene_slides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='layout',
            field=models.CharField(choices=[('100', 'Full Screen'), ('50', 'Half Screen'), ('33', 'Third Screen'), ('62', 'Golden Ratio')], default='100', max_length=20),
        ),
        migrations.CreateModel(
            name='SlideSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('chart', 'Chart')], default='text', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.slide')),
            ],
        ),
    ]
