# Generated by Django 4.2.30 on 2026-06-24 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_slide_layout_slidesection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='markdown',
        ),
    ]
