# Generated by Django 4.2.30 on 2026-09-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_settings_avatar_style_settings_carto_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='n_groups',
        ),
    ]
