# Generated by Django 4.2.30 on 2026-09-09 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_event_n_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.event'),
        ),
    ]
