# Generated by Django 4.2.30 on 2026-06-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_slide_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidesection',
            name='content_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
