# Generated by Django 4.2.30 on 2026-09-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_settings_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='dev_mode',
            field=models.BooleanField(default=False),
        ),
    ]
