# Generated by Django 4.2.30 on 2026-06-24 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_slidesection_content_path'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventscene',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='eventscene',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventscene',
            name='scene',
        ),
        migrations.DeleteModel(
            name='Format',
        ),
        migrations.RemoveField(
            model_name='event',
            name='scenes',
        ),
        migrations.DeleteModel(
            name='EventScene',
        ),
    ]
