# Generated by Django 4.2.30 on 2026-09-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_settings_dev_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='moderator_pin',
        ),
        migrations.AddField(
            model_name='settings',
            name='moderator_pin',
            field=models.CharField(default='', max_length=128),
        ),
    ]
