# Generated by Django 4.2.30 on 2026-06-26 15:05

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_eventscene_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='layout',
        ),
    ]
