# Generated by Django 4.2.30 on 2026-06-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_slide_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidesection',
            name='width_fraction',
            field=models.FloatField(default=1.0),
        ),
    ]
