# Generated by Django 4.2.30 on 2026-09-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_event_moderator_pin_settings_moderator_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='moderator_pin',
            field=models.CharField(max_length=128),
        ),
    ]
