# Generated by Django 4.2.30 on 2026-06-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_eventscene_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('current_scenes', models.IntegerField(default=1)),
                ('scenes', models.ManyToManyField(blank=True, related_name='presentations', to='core.scene')),
            ],
        ),
    ]
