# Generated by Django 4.2.30 on 2026-09-10 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_settings_moderator_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='pin_length',
            field=models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
