# Generated by Django 4.2.30 on 2026-06-26 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_slide_layout'),
        ('core', '0016_presentation'),
    ]

    operations = [
    ]
