# Generated by Django 4.2.30 on 2026-07-02 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_presentation'),
        ('core', '0016_slidesection_width_fraction'),
    ]

    operations = [
    ]
