# Generated by Django 5.2.15 on 2026-09-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_settings_pin_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='background_image_on_all_slides_per_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='background_image_on_empty_screens',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='background_image_on_welcome_screens',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='show_screen_id',
            field=models.BooleanField(default=False),
        ),
    ]
