# Generated by Django 4.2.30 on 2026-07-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20260702_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidesection',
            name='mode',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
