# Generated by Django 4.2.30 on 2026-07-01 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_slidesection_width_fraction'),
        ('core', '0017_merge_0015_remove_slide_layout_0016_presentation'),
    ]

    operations = [
    ]
