# Generated by Django 5.2.15 on 2026-07-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='URL_of_default_content_server',
            new_name='cs_url',
        ),
    ]
