# Generated by Django 5.2.15 on 2026-07-02 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20260702_1045'),
        ('core', '0020_rename_url_of_default_content_server_settings_cs_url'),
    ]

    operations = [
    ]
