# Generated by Django 5.2.15 on 2026-07-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_merge_20260702_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidesection',
            name='mode',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
