# Generated by Django 5.2.15 on 2026-07-03 10:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_slidesection_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scene',
            name='tags',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
