# Generated by Django 5.2.15 on 2026-07-04 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_scene_created_at_scene_tags_scene_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scene',
            name='slides',
        ),
        migrations.CreateModel(
            name='SlideInScenePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.scene')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.slide')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
