# Generated by Django 5.2.15 on 2026-07-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_scene_slides_slideinsceneposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='slides',
            field=models.ManyToManyField(blank=True, related_name='scenes', through='core.SlideInScenePosition', to='core.slide'),
        ),
    ]
