# Generated by Django 4.2.30 on 2026-10-09 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'core_parameterset',
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_presentation',
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'core_scene',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('width', models.IntegerField(default=1920)),
                ('height', models.IntegerField(default=1080)),
                ('tags', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'core_slide',
            },
        ),
        migrations.CreateModel(
            name='SlideInSlideshowPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.slide')),
            ],
            options={
                'db_table': 'core_slideinslideshowposition',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slides', models.ManyToManyField(blank=True, related_name='slideshows', through='content.SlideInSlideshowPosition', to='content.slide')),
            ],
            options={
                'db_table': 'core_slideshow',
            },
        ),
        migrations.CreateModel(
            name='SlideSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width_fraction', models.FloatField(default=1.0)),
                ('view_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('chart', 'Chart'), ('custom', 'Custom')], default='text', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('content_path', models.CharField(blank=True, max_length=255)),
                ('mode', models.CharField(blank=True, choices=[('static', 'Static'), ('url', 'URL'), ('interactive', 'Interactive')], max_length=20)),
                ('url_pattern', models.CharField(blank=True, default='', max_length=255)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.slide')),
            ],
            options={
                'db_table': 'core_slidesection',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='slideinslideshowposition',
            name='slideshow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.slideshow'),
        ),
        migrations.CreateModel(
            name='SlideInScenePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.scene')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.slide')),
            ],
            options={
                'db_table': 'core_slideinsceneposition',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='SceneInPresentationPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.presentation')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.scene')),
            ],
            options={
                'db_table': 'core_sceneinpresentationposition',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='scene',
            name='slides',
            field=models.ManyToManyField(blank=True, related_name='scenes', through='content.SlideInScenePosition', to='content.slide'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='scenes',
            field=models.ManyToManyField(blank=True, related_name='presentations', through='content.SceneInPresentationPosition', to='content.scene'),
        ),
        migrations.CreateModel(
            name='ParameterSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parameters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='content.parameterset')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_snapshots', to='content.slidesection')),
            ],
        ),
        migrations.AddField(
            model_name='parameterset',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_sets', to='content.slidesection'),
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ptype', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean'), ('select', 'Select'), ('location', 'Location')], default='string', max_length=20)),
                ('minimum', models.FloatField(blank=True, null=True)),
                ('maximum', models.FloatField(blank=True, null=True)),
                ('default', models.CharField(blank=True, max_length=255)),
                ('options', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('parameter_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='content.parameterset')),
            ],
            options={
                'db_table': 'core_parameter',
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('filetype', models.CharField(choices=[('geojson', 'GeoJSON'), ('gpkg', 'GPKG')], max_length=20)),
                ('file', models.FileField(upload_to='maplayers/')),
                ('marker', models.JSONField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('vector_type', models.CharField(choices=[('point', 'Point'), ('line', 'Line'), ('polygon', 'Polygon'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='content.slidesection')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('ptype', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean'), ('select', 'Select')], default='string', max_length=20)),
                ('pvalues', models.JSONField(blank=True, default=list)),
                ('connect_all', models.BooleanField()),
                ('connected_slide_parameters', models.ManyToManyField(related_name='my_parameters', to='content.parameter')),
            ],
            options={
                'db_table': 'core_globalparameter',
            },
        ),
    ]
