# Generated by Django 4.2.30 on 2026-07-28 14:00
# Hand-edited: wrapped operations in SeparateDatabaseAndState so this migration
# only updates Django's state (which app owns these models). The physical tables
# already exist as core_* (created while these models lived in the core app), so
# database_operations is empty and no SQL runs.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    state_operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_presentation',
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'core_scene',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('width', models.IntegerField(default=1920)),
                ('height', models.IntegerField(default=1080)),
                ('tags', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'core_slide',
            },
        ),
        migrations.CreateModel(
            name='SlideSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width_fraction', models.FloatField(default=1.0)),
                ('view_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('chart', 'Chart')], default='text', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('content_path', models.CharField(blank=True, max_length=255)),
                ('mode', models.CharField(blank=True, choices=[('static', 'Static'), ('url', 'URL'), ('interactive', 'Interactive')], max_length=20)),
                ('url_pattern', models.CharField(blank=True, default='', max_length=255)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.slide')),
            ],
            options={
                'db_table': 'core_slidesection',
            },
        ),
        migrations.CreateModel(
            name='SlideInScenePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.scene')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.slide')),
            ],
            options={
                'db_table': 'core_slideinsceneposition',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='SceneInPresentationPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.presentation')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.scene')),
            ],
            options={
                'db_table': 'core_sceneinpresentationposition',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='scene',
            name='slides',
            field=models.ManyToManyField(blank=True, related_name='scenes', through='content.SlideInScenePosition', to='content.slide'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='scenes',
            field=models.ManyToManyField(blank=True, related_name='presentations', through='content.SceneInPresentationPosition', to='content.scene'),
        ),
        migrations.CreateModel(
            name='ParameterSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_sets', to='content.slidesection')),
            ],
            options={
                'db_table': 'core_parameterset',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('ptype', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean'), ('select', 'Select')], default='string', max_length=20)),
                ('minimum', models.FloatField(blank=True, null=True)),
                ('maximum', models.FloatField(blank=True, null=True)),
                ('default', models.CharField(blank=True, max_length=255)),
                ('options', models.JSONField(blank=True, default=list)),
                ('parameter_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='content.parameterset')),
            ],
            options={
                'db_table': 'core_parameter',
            },
        ),
        migrations.CreateModel(
            name='LivePresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('current_scene', models.IntegerField(default=0)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_presentation', to='content.presentation')),
            ],
            options={
                'db_table': 'core_livepresentation',
            },
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
            database_operations=[],
        ),
    ]