# Generated by Django 4.2.30 on 2026-08-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidesection',
            name='view_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('chart', 'Chart'), ('custom', 'Custom')], default='text', max_length=20),
        ),
    ]
