# Generated by Django 4.2.30 on 2026-08-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_slidesection_view_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('filetype', models.CharField(choices=[('geojson', 'GeoJSON'), ('gpkg', 'GPKG')], max_length=20)),
                ('file', models.FileField(upload_to='layers/')),
                ('marker', models.JSONField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
