# Generated by Django 4.2.30 on 2026-08-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_layer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='file',
            field=models.FileField(upload_to='local/maplayers/'),
        ),
    ]
