# Generated by Django 4.2.30 on 2026-08-26 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_layer_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='content.slidesection'),
        ),
    ]
