# Generated by Django 4.2.30 on 2026-08-26 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_layer_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='content.slidesection'),
        ),
    ]
