# Generated by Django 5.2.15 on 2026-08-29 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_layer_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideInSlideshowPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.slide')),
            ],
            options={
                'db_table': 'core_slideinslideshowposition',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slides', models.ManyToManyField(blank=True, related_name='slideshows', through='content.SlideInSlideshowPosition', to='content.slide')),
            ],
            options={
                'db_table': 'core_slideshow',
            },
        ),
        migrations.AddField(
            model_name='slideinslideshowposition',
            name='slideshow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.slideshow'),
        ),
    ]
