# Generated by Django 4.2.30 on 2026-09-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_slideinslideshowposition_slideshow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='file',
            field=models.FileField(upload_to='maplayers/'),
        ),
    ]
