# Generated by Django 4.2.30 on 2026-09-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_layer_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='vectorType',
            field=models.CharField(choices=[('point', 'Point'), ('line', 'Line'), ('polygon', 'Polygon'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
