# Generated by Django 4.2.30 on 2026-09-10 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_layer_vectortype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layer',
            old_name='vectorType',
            new_name='vector_type',
        ),
    ]
