# Generated by Django 4.2.30 on 2026-09-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_rename_vectortype_layer_vector_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='ptype',
            field=models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean'), ('select', 'Select'), ('location', 'Location')], default='string', max_length=20),
        ),
        migrations.DeleteModel(
            name='LivePresentation',
        ),
    ]
