# Generated by Django 5.2.15 on 2026-09-15 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_rename_vectortype_layer_vector_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LivePresentation',
        ),
    ]
