# Generated by Django 4.2.30 on 2026-09-17 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_parameter_ptype_delete_livepresentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parameters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='content.parameterset')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_snapshots', to='content.slidesection')),
            ],
        ),
    ]
