# Generated by Django 4.2.30 on 2026-09-28 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_parametersnapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slidesection',
            options={'ordering': ['id']},
        ),
    ]
