# Generated by Django 5.2.15 on 2026-10-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_alter_slidesection_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('ptype', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean'), ('select', 'Select')], default='string', max_length=20)),
                ('connect_all', models.BooleanField()),
            ],
            options={
                'db_table': 'core_globalparameter',
            },
        ),
    ]
