# Generated by Django 5.2.15 on 2026-10-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_globalparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalparameter',
            name='pvalues',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
